#include "NavoEthernetTransport.h"
#include <QHostAddress>
#include <QNetworkDatagram>
NavoEthernetTransport::NavoEthernetTransport(QObject*p):QObject(p){connect(&_tcp,&QTcpSocket::connected,this,&NavoEthernetTransport::connected);connect(&_tcp,&QTcpSocket::disconnected,this,&NavoEthernetTransport::disconnected);connect(&_tcp,&QTcpSocket::readyRead,this,&NavoEthernetTransport::readTcp);connect(&_tcp,&QTcpSocket::errorOccurred,this,[this](auto){emit errorOccurred(_tcp.errorString());});connect(&_udpSocket,&QUdpSocket::readyRead,this,&NavoEthernetTransport::readUdp);connect(&_watchdog,&QTimer::timeout,this,&NavoEthernetTransport::checkWatchdog);_watchdog.start(1000);}
void NavoEthernetTransport::setHost(const QString&v){if(_host==v)return;_host=v;emit hostChanged();}void NavoEthernetTransport::setPort(int v){if(_port==v)return;_port=v;emit portChanged();}void NavoEthernetTransport::setUdp(bool v){if(_udp==v)return;_udp=v;emit udpChanged();}void NavoEthernetTransport::setTimeoutMs(int v){v=qMax(500,v);if(_timeoutMs==v)return;_timeoutMs=v;emit timeoutMsChanged();}
void NavoEthernetTransport::connectLink(){disconnectLink();_lastData.invalidate();if(_udp){QHostAddress a(_host);if(!_udpSocket.bind(QHostAddress::AnyIPv4,quint16(_port),QUdpSocket::ShareAddress|QUdpSocket::ReuseAddressHint)){emit errorOccurred(_udpSocket.errorString());return;}emit connected();}else _tcp.connectToHost(_host,quint16(_port));}
void NavoEthernetTransport::disconnectLink(){if(_udpSocket.state()!=QAbstractSocket::UnconnectedState)_udpSocket.close();_tcp.abort();}
void NavoEthernetTransport::writeBytes(const QByteArray&b){if(_udp){QHostAddress a(_host);_udpSocket.writeDatagram(b,a,quint16(_port));}else if(_tcp.state()==QTcpSocket::ConnectedState)_tcp.write(b);}
void NavoEthernetTransport::readTcp(){auto b=_tcp.readAll();if(!b.isEmpty()){noteData();emit bytesReceived(b);}}void NavoEthernetTransport::readUdp(){while(_udpSocket.hasPendingDatagrams()){auto d=_udpSocket.receiveDatagram();if(!d.data().isEmpty()){noteData();emit bytesReceived(d.data());}}}
void NavoEthernetTransport::noteData(){_lastData.restart();if(_stale){_stale=false;emit staleChanged();}}
void NavoEthernetTransport::checkWatchdog(){bool s=_lastData.isValid()&&_lastData.elapsed()>_timeoutMs;if(s!=_stale){_stale=s;emit staleChanged();}}
