#include "NavoEthernetTransport.h"
#include <QHostAddress>
#include <QNetworkDatagram>
NavoEthernetTransport::NavoEthernetTransport(QObject*p):QObject(p){_healthTimer.setInterval(1000);connect(&_healthTimer,&QTimer::timeout,this,&NavoEthernetTransport::healthTick);_healthTimer.start();_reconnectTimer.setSingleShot(true);_reconnectTimer.setInterval(3000);connect(&_reconnectTimer,&QTimer::timeout,this,&NavoEthernetTransport::connectEndpoint);connect(&_tcp,&QTcpSocket::connected,this,[this]{setConnected(true);setStatus("LIVE");});connect(&_tcp,&QTcpSocket::disconnected,this,[this]{setConnected(false);setDataAlive(false);setStatus("OFFLINE");scheduleReconnect();});connect(&_tcp,&QTcpSocket::readyRead,this,&NavoEthernetTransport::readTcp);connect(&_udpSocket,&QUdpSocket::readyRead,this,&NavoEthernetTransport::readUdp);connect(&_tcp,&QTcpSocket::errorOccurred,this,[this](QAbstractSocket::SocketError){setStatus(_tcp.errorString());scheduleReconnect();});}
void NavoEthernetTransport::setHost(const QString&v){if(_host!=v){_host=v;emit endpointChanged();}}void NavoEthernetTransport::setPort(quint16 v){if(_port!=v){_port=v;emit endpointChanged();}}void NavoEthernetTransport::setUdp(bool v){if(_udp!=v){_udp=v;emit endpointChanged();}}void NavoEthernetTransport::setAutoReconnect(bool v){if(_autoReconnect!=v){_autoReconnect=v;if(!v)_reconnectTimer.stop();emit autoReconnectChanged();}}
void NavoEthernetTransport::setConnected(bool v){if(_connected!=v){_connected=v;emit connectedChanged();}}void NavoEthernetTransport::setDataAlive(bool v){if(_dataAlive!=v){_dataAlive=v;emit dataAliveChanged();}}void NavoEthernetTransport::setStatus(const QString&v){if(_status!=v){_status=v;emit statusChanged();}}
void NavoEthernetTransport::disconnectEndpoint(){_manualDisconnect=true;_reconnectTimer.stop();_tcp.abort();_udpSocket.close();setConnected(false);setDataAlive(false);setStatus("OFFLINE");}
void NavoEthernetTransport::connectEndpoint(){_manualDisconnect=false;_reconnectTimer.stop();_tcp.abort();_udpSocket.close();setConnected(false);setDataAlive(false);if(_host.isEmpty()||!_port){setStatus("ENDPOINT INVALID");return;}setStatus("CONNECTING");if(_udp){QHostAddress a;if(!a.setAddress(_host)){setStatus("UDP HOST INVALID");return;}if(!_udpSocket.bind(QHostAddress::AnyIPv4,0)){setStatus(_udpSocket.errorString());scheduleReconnect();return;}setConnected(true);setStatus("UDP READY");}else _tcp.connectToHost(_host,_port);}
void NavoEthernetTransport::scheduleReconnect(){if(_autoReconnect&&!_manualDisconnect&&!_host.isEmpty()&&_port&&!_reconnectTimer.isActive())_reconnectTimer.start();}void NavoEthernetTransport::noteData(){_lastData.restart();setDataAlive(true);if(_connected)setStatus("LIVE");}
void NavoEthernetTransport::healthTick(){if(_dataAlive&&_lastData.isValid()&&_lastData.elapsed()>5000){setDataAlive(false);setStatus("NO DATA");if(!_udp&&_connected){_tcp.abort();scheduleReconnect();}}}
void NavoEthernetTransport::readTcp(){auto b=_tcp.readAll();if(!b.isEmpty()){noteData();emit bytesReceived(b);}}void NavoEthernetTransport::readUdp(){while(_udpSocket.hasPendingDatagrams()){auto d=_udpSocket.receiveDatagram();if(!d.data().isEmpty()){noteData();emit bytesReceived(d.data());}}}