cmake_minimum_required(VERSION 3.16)
project(NavoPersistenceTests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
find_package(Qt6 REQUIRED COMPONENTS Core Test)
add_executable(navo-persistence-test persistence.cpp ../../custom/src/NavoPersistence.cc ../../custom/src/NavoPersistence.h)
target_link_libraries(navo-persistence-test PRIVATE Qt6::Core Qt6::Test)
