import QtQuick
import QtQuick.Controls
import QtQuick3D
import QtPositioning
import NavoSmart.Backend 1.0
Item {
 id:root
 property var samples:[]; property var boatTrack:[]; property var waypoints:[]; property var fishingSpots:[]; property var fishDetections:[]
 property real gridSizeM:2; property real maxGapM:6; property real verticalExaggeration:2; property real yaw:-35; property real pitch:-48; property real cameraDistance:180; property point panOffset:Qt.point(0,0)
 property var selectedPoint:null; property var selectedObject:null; property string selectedKind:""
 property bool showTrack:true; property bool showWaypoints:true; property bool showSpots:true; property bool showFish:true; property int maxTrackPoints3D:1200; property int maxFish3D:500\n readonly property int lodLevel: cameraDistance>500?3:cameraDistance>250?2:cameraDistance>110?1:0\n readonly property int adaptiveTrackLimit: lodLevel===3?180:lodLevel===2?350:lodLevel===1?700:maxTrackPoints3D\n readonly property int adaptiveFishLimit: lodLevel===3?60:lodLevel===2?140:lodLevel===1?280:maxFish3D
 function rebuild(){meshEngine.build(samples,gridSizeM,maxGapM)}
 function resetCamera(){yaw=-35;pitch=-48;cameraDistance=180;panOffset=Qt.point(0,0)} function topCamera(){yaw=0;pitch=-89;cameraDistance=180} function isoCamera(){yaw=-45;pitch=-42;cameraDistance=180}
 function localPoint(lat,lon,depth){var R=6378137,lat0=meshEngine.originLatitude*Math.PI/180,x=(lon-meshEngine.originLongitude)*Math.PI/180*Math.cos(lat0)*R,z=-(lat-meshEngine.originLatitude)*Math.PI/180*R,y=-(depth||0)*verticalExaggeration;return Qt.vector3d(x,y,z)}
 function bottomDepth(lat,lon){var best=null,bd=1e99,p=localPoint(lat,lon,0);for(var i=0;i<meshEngine.vertices.length;i++){var v=meshEngine.vertices[i],d=(v.x-p.x)*(v.x-p.x)+((-v.y)-p.z)*((-v.y)-p.z);if(d<bd){bd=d;best=v}}return best?best.depth:0}
 function decimate(a,max){if(!a||a.length<=max)return a||[];var out=[],step=(a.length-1)/(max-1);for(var i=0;i<max;i++)out.push(a[Math.round(i*step)]);return out}\n function trackLocal(){var a=decimate(boatTrack,adaptiveTrackLimit),o=[];for(var i=0;i<a.length;i++){var p=a[i],v=localPoint(p.latitude!==undefined?p.latitude:p.lat,p.longitude!==undefined?p.longitude:p.lon,0);o.push({x:v.x,y:v.y+.15,z:v.z})}return o}\n function labelPoint(o,kind){if(kind==="waypoint")return localPoint(o.lat!==undefined?o.lat:o.coordinate.latitude,o.lon!==undefined?o.lon:o.coordinate.longitude,Math.max(0,bottomDepth(o.lat!==undefined?o.lat:o.coordinate.latitude,o.lon!==undefined?o.lon:o.coordinate.longitude)-.7));return localPoint(o.lat,o.lon,Math.max(0,(o.depth!==null&&o.depth!==undefined?o.depth:bottomDepth(o.lat,o.lon))-.8))}
 function select(kind,obj){selectedKind=kind;selectedObject=obj;selectedPoint=null}
 function fmtTime(v){if(!v)return "--";return new Date(v).toLocaleString(Qt.locale(),"dd MMM yyyy HH:mm:ss")}
 NavoBathymetryMesh{id:meshEngine}
 Rectangle{anchors.fill:parent;color:"#071019"}
 View3D{id:view;anchors.fill:parent;camera:camera;environment:SceneEnvironment{clearColor:"#071019";backgroundMode:SceneEnvironment.Color;antialiasingMode:SceneEnvironment.MSAA;antialiasingQuality:SceneEnvironment.High}
  PerspectiveCamera{id:camera;position:Qt.vector3d(root.panOffset.x,65+root.panOffset.y,root.cameraDistance);eulerRotation.x:root.pitch;eulerRotation.y:root.yaw;clipNear:.1;clipFar:5000}
  DirectionalLight{eulerRotation.x:-45;eulerRotation.y:-35;brightness:1.15;castsShadow:true} DirectionalLight{eulerRotation.x:35;eulerRotation.y:145;brightness:.35}
  Model{id:terrain;pickable:true;geometry:NavoBathymetryGeometry{vertices:meshEngine.vertices;triangles:meshEngine.triangles;verticalExaggeration:root.verticalExaggeration;minDepth:meshEngine.minDepthM;maxDepth:meshEngine.maxDepthM}materials:PrincipledMaterial{vertexColorsEnabled:true;roughness:.72;cullMode:Material.NoCulling}}
  Node{id:overlayRoot
   Repeater3D{model:root.showWaypoints?root.waypoints:[];delegate:Model{id:wp;required property var modelData;property string kind:"waypoint";pickable:true;position:root.localPoint(modelData.lat!==undefined?modelData.lat:modelData.coordinate.latitude,modelData.lon!==undefined?modelData.lon:modelData.coordinate.longitude,Math.max(0,root.bottomDepth(modelData.lat!==undefined?modelData.lat:modelData.coordinate.latitude,modelData.lon!==undefined?modelData.lon:modelData.coordinate.longitude)-.7));source:"#Sphere";scale:Qt.vector3d(.8,.8,.8);materials:PrincipledMaterial{baseColor:"#ffd54f";emissiveFactor:Qt.vector3d(.25,.18,0)}}}
   Repeater3D{model:root.showSpots?root.fishingSpots:[];delegate:Model{id:spot;required property var modelData;property string kind:"spot";pickable:true;position:root.localPoint(modelData.lat,modelData.lon,Math.max(0,(modelData.depth!==null&&modelData.depth!==undefined?modelData.depth:root.bottomDepth(modelData.lat,modelData.lon))-.8));source:"#Cylinder";scale:Qt.vector3d(.45,1.4,.45);materials:PrincipledMaterial{baseColor:"#ff8a3d"}}}
   Repeater3D{model:root.showFish?root.decimate(root.fishDetections,root.adaptiveFishLimit):[];delegate:Model{id:fish;required property var modelData;property string kind:"fish";pickable:true;position:root.localPoint(modelData.lat,modelData.lon,modelData.targetDepth||0);source:"#Sphere";scale:Qt.vector3d(.38,.22,.65);materials:PrincipledMaterial{baseColor:(modelData.strength!==null&&modelData.strength>.65)?"#ff5252":"#67e480";emissiveFactor:Qt.vector3d(.15,.15,.15)}}}
   Model{visible:root.showTrack;geometry:NavoTrack3DGeometry{points:root.trackLocal();width:.38}materials:PrincipledMaterial{baseColor:"#21b7ff";emissiveFactor:Qt.vector3d(.1,.35,.5);cullMode:Material.NoCulling}}
  }
 }
 TapHandler{onTapped:function(e){var p=view.pick(e.position.x,e.position.y);if(!p.objectHit){selectedObject=null;selectedPoint=null;return}if(p.objectHit.kind){root.select(p.objectHit.kind,p.objectHit.modelData);return}if(p.objectHit===terrain){var best=null,bd=1e99;for(var i=0;i<meshEngine.vertices.length;i++){var v=meshEngine.vertices[i],dx=v.x-p.scenePosition.x,dz=(-v.y)-p.scenePosition.z,d=dx*dx+dz*dz;if(d<bd){bd=d;best=v}}selectedPoint=best;selectedObject=null;selectedKind="bottom"}}}}
 DragHandler{target:null;acceptedButtons:Qt.LeftButton;onTranslationChanged:{root.yaw+=translation.x*.18;root.pitch=Math.max(-82,Math.min(-8,root.pitch-translation.y*.14))}} PinchHandler{target:null;onScaleChanged:root.cameraDistance=Math.max(12,Math.min(1800,root.cameraDistance/scale))} WheelHandler{onWheel:root.cameraDistance=Math.max(12,Math.min(1800,root.cameraDistance*(wheel.angleDelta.y>0?.9:1.1)))}
 Row{anchors{top:parent.top;left:parent.left;margins:12}spacing:5;Button{text:"Top";onClicked:root.topCamera()}Button{text:"ISO";onClicked:root.isoCamera()}Button{text:"Reset";onClicked:root.resetCamera()}Button{text:"1×";onClicked:root.verticalExaggeration=1}Button{text:"2×";onClicked:root.verticalExaggeration=2}Button{text:"3×";onClicked:root.verticalExaggeration=3}Button{text:"5×";onClicked:root.verticalExaggeration=5}}
 Row{anchors{top:parent.top;right:parent.right;margins:12}spacing:4;CheckBox{text:"Traseu";checked:root.showTrack;onToggled:root.showTrack=checked}CheckBox{text:"WP";checked:root.showWaypoints;onToggled:root.showWaypoints=checked}CheckBox{text:"Locuri";checked:root.showSpots;onToggled:root.showSpots=checked}CheckBox{text:"Pești";checked:root.showFish;onToggled:root.showFish=checked}}
 Rectangle{visible:root.selectedObject!==null||root.selectedPoint!==null;anchors{left:parent.left;bottom:parent.bottom;margins:12}width:310;height:details.implicitHeight+24;radius:8;color:"#d9101c29";border.color:"#45677e"
  Column{id:details;anchors{left:parent.left;right:parent.right;top:parent.top;margins:12}spacing:4
   Text{color:"white";font.bold:true;text:selectedKind==="waypoint"?"Waypoint: "+(selectedObject?(selectedObject.name||selectedObject.friendlyName||"WP"):""):selectedKind==="spot"?"Loc pescuit: "+(selectedObject?(selectedObject.name||""):""):selectedKind==="fish"?"Detecție pește":"Fund lac"}
   Text{color:"white";text:selectedKind==="fish"&&selectedObject?"Adâncime pește: "+Number(selectedObject.targetDepth).toFixed(2)+" m":selectedObject&&selectedObject.depth!==undefined&&selectedObject.depth!==null?"Adâncime: "+Number(selectedObject.depth).toFixed(2)+" m":selectedPoint?"Adâncime: "+Number(selectedPoint.depth).toFixed(2)+" m":""}
   Text{color:"white";visible:selectedObject&&selectedObject.temp!==undefined&&selectedObject.temp!==null;text:visible?"Temperatură: "+Number(selectedObject.temp).toFixed(1)+" °C":""}
   Text{color:"white";visible:selectedObject&&(selectedObject.time||selectedObject.createdAt);text:visible?"Timp: "+root.fmtTime(selectedObject.time||selectedObject.createdAt):""}
   Text{color:"white";visible:selectedPoint!==null;text:visible?(selectedPoint.measured?"Măsurat":"Interpolat")+" • confidence "+Math.round(selectedPoint.confidence*100)+"%":""}
   Text{color:"white";visible:selectedObject&&selectedObject.strength!==undefined&&selectedObject.strength!==null;text:visible?"Intensitate sonar: "+Number(selectedObject.strength).toFixed(2):""}
  }}
 Column{anchors{right:parent.right;bottom:parent.bottom;margins:12}spacing:5;Rectangle{width:180;height:18;gradient:Gradient{orientation:Gradient.Horizontal;GradientStop{position:0;color:"#0db8c7"}GradientStop{position:.5;color:"#0a3d9e"}GradientStop{position:1;color:"#330a61"}}}Text{color:"white";text:Number(meshEngine.minDepthM).toFixed(1)+" m                         "+Number(meshEngine.maxDepthM).toFixed(1)+" m"}Text{color:"white";text:meshEngine.measuredVertexCount+" măsurate • "+meshEngine.interpolatedVertexCount+" interpolate • LOD "+root.lodLevel}}
 Component.onCompleted:if(samples.length)rebuild();onSamplesChanged:if(samples.length)rebuild()
}